import {
  Code2,
  Globe,
  Megaphone,
  Search,
  TrendingUp,
  Smartphone,
  ClipboardList,
  GraduationCap,
  ShieldCheck,
  BedDouble,
  School,
  BookOpen,
  Sprout,
  Receipt,
  Building2,
  Languages,
  Scan,
  Glasses,
  Users,
  FileBadge,
  Cpu,
  ShoppingCart,
  Vote,
  BookUser,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  Code2,
  Globe,
  Megaphone,
  Search,
  TrendingUp,
  Smartphone,
  ClipboardList,
  GraduationCap,
  ShieldCheck,
  BedDouble,
  School,
  BookOpen,
  Sprout,
  Receipt,
  Building2,
  Languages,
  Scan,
  Glasses,
  Users,
  FileBadge,
  Cpu,
  ShoppingCart,
  Vote,
  BookUser,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = iconMap[name] ?? Code2;
  return <Component className={className} />;
}
